import { ReactFlow, Position, Handle } from "@xyflow/react";

export const AllNodes = [
  {
    id: "nl1-1",
    sourcePosition: Position.Right,
    position: { x: 20, y: 0 },
    isParent: true,
    type: "custom",

    data: {
      id: "nl1-1",
      isSource: true,
      isSolutionPlay: true,
      label: "Unify your Intelligent Data and Analytics Platform",
      nodes: ["nl2-1", "nl2-2", "nl2-3", "nl2-6"],
      isDisabled: false,
      isActive: true,
    },
  },
  {
    id: "nl1-2",
    sourcePosition: Position.Right,
    position: { x: 20, y: 70 },
    isParent: true,
    type: "custom",
    data: {
      id: "nl1-2",
      isSolutionPlay: true,
      isSource: true,
      label: "Innovate with Azure AI Platform",
      nodes: ["nl2-1", "nl2-5"],
      isDisabled: false,
    },
  },
  {
    id: "nl1-3",
    sourcePosition: Position.Right,
    position: { x: 20, y: 140 },
    isParent: true,

    type: "custom",
    data: {
      id: "nl1-3",
      isSolutionPlay: true,
      isSource: true,
      label: "Build and Modernize AI Apps",
      nodes: ["nl2-1", "nl2-4", "nl2-5"],
      isDisabled: false,
    },
  },
  {
    id: "nl1-4",
    sourcePosition: Position.Right,
    position: { x: 20, y: 210 },
    type: "custom",
    isParent: true,

    data: {
      id: "nl1-4",
      isSolutionPlay: true,
      isSource: true,
      label: "Data Security",
      nodes: ["nl2-1", "nl2-6"],
      isDisabled: false,
    },
  },
  {
    id: "nl2-1",
    position: { x: 350, y: 0 },
    type: "custom",
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    data: {
      id: "nl2-1",
      label: "End-to-End Demo",
      isDisabled: true,
      nodes: [
        "nl3-1",
        "nl3-2",
        "nl3-3",
        "nl3-4",
        "nl3-5",
        "nl3-6",
        "nl3-7",
        "nl3-8",
        "nl3-9",
        "nl3-10",
        "nl3-11",
        "nl3-12",
        "nl3-13",
        "nl3-14",
        "nl3-15",
        "nl3-16",
        "nl3-17",
      ],
    },
  },
  {
    id: "nl2-2",
    position: { x: 350, y: 70 },
    type: "custom",
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    data: {
      id: "nl2-2",
      label: "Microsoft Fabric",
      isDisabled: true,
      nodes: [
        "nl3-1",
        "nl3-2",
        "nl3-3",
        "nl3-4",
        "nl3-5",
        "nl3-6",
        "nl3-7",
        "nl3-11",
        "nl3-14",
        "nl3-17",
      ],
    },
  },
  {
    id: "nl2-3",
    position: { x: 350, y: 140 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-3",
      label: "Microsoft Fabric + Azure Databricks",
      nodes: ["nl3-8"],
      isDisabled: true,
    },
  },
  {
    id: "nl2-4",
    position: { x: 350, y: 210 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-4",
      label: "Apps + Azure Cosmos DB",
      nodes: ["nl3-9"],
      isDisabled: true,
    },
  },
  {
    id: "nl2-5",
    position: { x: 350, y: 280 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-5",
      label: "AI Design Wins",
      nodes: ["nl3-12", "nl3-13", "nl3-15", "nl3-16"],
      isDisabled: true,
    },
  },
  {
    id: "nl2-6",
    position: { x: 350, y: 350 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-6",
      label: "Microsoft Purview",
      nodes: ["nl3-10"],
      isDisabled: true,
    },
  },
  {
    id: "nl3-1",
    position: { x: 680, y: 0 },
    type: "custom",
    targetPosition: Position.Right,
    sourcePosition: Position.Left,

    level: 3,
    data: {
      id: "nl3-1",
      label: "Data Engineering",
      level: 3,
      isDisabled: true,
      url: "#/data-engineering",
    },
  },
  {
    id: "nl3-2",
    position: { x: 680, y: 50 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-2",
      label: "Data Factory",
      level: 3,
      isDisabled: true,
      url: "#/dataflow-gen2",
    },
  },

  {
    id: "nl3-3",
    position: { x: 680, y: 100 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-3",
      label: "Data Science",
      level: 3,
      isDisabled: true,
      url: "#/notebook-copilot",
    },
  },
  {
    id: "nl3-4",
    position: { x: 680, y: 150 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-4",
      label: "Data Warehouse",
      level: 3,
      isDisabled: true,
      url: "#/operating-profits",
    },
  },
  {
    id: "nl3-5",
    position: { x: 680, y: 200 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-5",
      label: "Real-Time Intelligence & Data Activator",
      level: 3,
      isDisabled: true,
      url: "#/real-time-intelligence",
    },
  },
  {
    id: "nl3-6",
    position: { x: 680, y: 250 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-6",
      label: "Copilot for Power BI in Microsoft Fabric",
      level: 3,
      isDisabled: true,
      url: "#/powerbi-experience",
    },
  },
  {
    id: "nl3-14",
    position: { x: 680, y: 300 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-14",
      label: "Configurable Demo for Copilot in Microsoft Fabric",
      level: 3,
      isDisabled: true,
      url: "https://app-configurable-pbi-copilot-common-demo.azurewebsites.net/",
    },
  },
  // {
  //   id: "nl3-7",
  //   position: { x: 680, y: 400 },
  //   type: "custom",
  //   targetPosition: Position.Left,
  //   level: 3,

  //   data: {
  //     id: "nl3-7",
  //     label: "Data Activator",
  //     level: 3,
  //     isDisabled: true,
  //     url: "#/real-time-intelligence",
  //   },
  // },
  {
    id: "nl3-8",
    position: { x: 680, y: 450 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-8",
      label: "Mirrored Azure Databricks Catalog",
      level: 3,
      isDisabled: true,
      url: "#/with-microsoft-fabric-and-azure-databricks",
    },
  },
  {
    id: "nl3-9",
    position: { x: 680, y: 500 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-9",
      label: "Apps + Azure Cosmos DB",
      level: 3,
      isDisabled: true,
      url: "#/apps-azure-cosmos-db-highlights",
    },
  },
  {
    id: "nl3-10",
    position: { x: 680, y: 550 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-10",
      label: "Data Governance",
      level: 3,
      isDisabled: true,
      url: "#/purview-overview-video",
    },
  },

  {
    id: "nl3-16",
    position: { x: 680, y: 600 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-16",
      label: "Chatbot for Enterprise Data",
      level: 3,
      isDisabled: true,
      url: "#/enterprise-chatbot",
    },
  },
  {
    id: "nl3-15",
    position: { x: 680, y: 650 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-15",
      label: "Build Your Own Shopping Assistant",
      level: 3,
      isDisabled: true,
      url: "#/copilot-wardrobe-selection",
    },
  },
  {
    id: "nl3-11",
    position: { x: 680, y: 350 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-11",
      label: "Databases",
      level: 3,
      isDisabled: true,
      url: "#/operating-profits",
    },
  },
  {
    id: "nl3-17",
    position: { x: 680, y: 400 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-17",
      label: "End to End Microsoft Fabric Click by Click",
      level: 3,
      isDisabled: true,
      url: "#/fabric-click-by-click",
    },
  },
  {
    id: "nl3-12",
    position: { x: 680, y: 700 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-12",
      label: "Predicting Customer Churn",
      level: 3,
      isDisabled: true,
      url: "#/customer-review",
    },
  },
  {
    id: "nl3-13",
    position: { x: 680, y: 750 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-13",
      label: "Build your own Contact Center Assistant",
      level: 3,
      isDisabled: true,
      url: "#/customer-call-in-progress",
    },
  },
];
